version: '3'
services:
  db:
    image: mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: crm
      MYSQL_USER: crm_admin
      MYSQL_PASSWORD: password