version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: crm
      POSTGRES_USER: crm_admin
      POSTGRES_PASSWORD: password
      #volumes:
#      - "crmdata:/var/lib/postgresql/data"
#volumes:
#  crmdata: